### ISSUE TITLE
Security caveats with docker-compose

### ISSUE THREAD

**Issue by programmador** [PacktPublishing/Keycloak-Identity-and-Access-Management-for-Modern-Applications#9]
I'm running all the examples with docker-compose and have encountered few issues which took pretty while to fix and which are not covered in the book. I don't know which of the issues are related to running everything including keycloak itself with docker-compose and which are not. Anyway I hope my info could be helpful at least being here for anyone who will want to try examples the same way as me. Probably it will be worth covering by next editions of the book.

Obviously Keycloak in docker-compose environment receives queries not from 127.0.0.1 and consequently does not disable some security stuff which is disabled for localhost.

So far I've sucessfully run examples from ch2 and ch4. So the main caveats I've encountered actually are:

1. From scratch Keycloak blaims that it wants HTTPS. So examples from the book won't be reproducable as You won't be able to login as admin. Running few commands in docker container's bash console helped (do not do it in production env):
```shell
# docker-compose exec keycloak bash
/opt/jboss/keycloak/bin/kcadm.sh config credentials --server http://localhost:8080/auth --realm master --user admin
# enter password
/opt/jboss/keycloak/bin/kcadm.sh update realms/master -s sslRequired=NONE
```
2. Do not ever try to map ports for keycloak server. For example I didn't want to use 8080 as it was already bound by another service and set up `ports: [ '8082:8080' ]`. This is the wrong way. Keycloak v15 blaims that Promise timeout exceeded which is not truth actually. I've downgraded Keycloak to v12 (changes are present in KC_URL/js/keycloak.json), disabled CORS in browser with a plugin and got Http 406 response from jboss server which blamed the same: CORS. I've googled a lot and found nothing helpful. After some time a thought about CORS URL mismatch due to port mapping visited my head suddenly. So I've _actually started keycloak on another port_ instead of _mapping the port_. It helped.
3. I was happy until I tried accessing the secured backend endpoint via frontend. Frontend always got 403 though an appropriate role was added to the user as the book emphasizes in a tip. I've googled a lot again and went to nodejs client documentation where I've found an interesting config parameter: realmPublicKey. It was easy to find it in Keycloak admin console and to put into ch2/backend/keycloak.json as follows (be sure to use public key from Your realm config):
```json
{
  "realm": "myrealm",
  "bearer-only": true,
  "auth-server-url": "${env.KC_URL:http://localhost:8082/auth}",
  "resource": "service-nodejs",
  "realmPublicKey": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmho2TQKxPWpE57iWhkF90odTL9VwRhPPbwqLgBCJ2a+qoEoV0N4MxjjHiDj/GuEO9QJK/F8RqOcA+oY+O1XFm4BRT0JoDTS97IaPYBM4aKHyiYNVLRilqXP1E6RnoPH6kaSrikX16z7/6I7yDtR1Yid4wpTVAeHxdFEyzm05l7m9UkaQNuYdA3vsah4xg2qKLST1Rou9uMwHqRq+X3Dovl0iNf+9ECa4aDISy88/o9CdeqlYNccmh7CQmcFPz5iSDa2ncojJYy1MWd1fjsF7xUKZWgIU0LicJfT/P/7GXA3k0tIDsA22uWElMaeqSkvoiLL+5PNAMKNHL0c1iQ1slwIDAQAB"
}
```

Eventually I'm attaching my docker-compose.yml contents for reference:
```yaml
version: '3.8'

services:
  keycloak:
    #image: quay.io/keycloak/keycloak:15.0.0
    image: quay.io/keycloak/keycloak:12.0.0
    #image: bitnami/keycloak:12
    container_name: keycloak-server
    restart: "no"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      ROOT_LOGLEVEL: "${KC_ROOT_LOGLEVEL}" 
      # KEYCLOAK_HTTP:PORT: 8082 # for bitnami
    volumes:
      - './db:/opt/jboss/keycloak/standalone/data'
    ports:
      - "8082:8082"
    command: ["-Djboss.socket.binding.port-offset=2"] # for quay.io(jboss)

  frontend_ch2:
    build:
      context: ../book/ch2/frontend
    ports:
      - "8000:8000"
    restart: "no"

  backend_ch2:
    build:
      context: ../book/ch2/backend
    ports:
      - "3000:3000"
    restart: "no"

#  frontend_ch4:
#    build:
#      context: ../book/ch4
#    ports:
#      - "8000:8000"
#    restart: "no"
```
Be sure to use proper paths with source code and to disable keycloak's 8080->8082 port reconfiguration if You don't need it.
I'm mounting the embedded H2 DB folder to preserve data between starts.
Pay attention that H2 is default form jboss images while bitnami images though offering a fancy env var to configure HTTP port are using Postgres by default which will require additional docker-compose service accordingly (perhaps with it's own mounted DB dir).
